name: lstm_pred
channels:
  - pytorch
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.8.12
  - pytorch=1.10.0
  - pip:
    - jupyter==1.0.0
    - matplotlib==3.5.2
    - numpy==1.22.3
    - pandas==1.4.2
    - scikit-learn==1.0.2
    - seaborn==0.11.2
    - tqdm==4.64.0
    - openpyxl == 3.0.10
    - geopy == 2.4.0
    - xarray == 2023.1.0
    - cftime == 1.6.2
    - keras == 2.13.1
    - tensorflow == 2.13.1

